export const mockedMovies = [
  {
    adult: false,
    backdrop_path: '/1X7vow16X7CnCoexXh4H4F2yDJv.jpg',
    genre_ids: [80, 18, 36],
    id: 466420,
    original_language: 'en',
    original_title: 'Killers of the Flower Moon',
    overview:
      'When oil is discovered in 1920s Oklahoma under Osage Nation land, the Osage people are murdered one by one—until the FBI steps in to unravel the mystery.',
    popularity: 1414.987,
    poster_path: '/dB6Krk806zeqd0YNp2ngQ9zXteH.jpg',
    release_date: '2023-10-18',
    title: 'Killers of the Flower Moon',
    video: false,
    vote_average: 7.64,
    vote_count: 1400,
  },
  {
    adult: false,
    backdrop_path: '/zIYROrkHJPYB3VTiW1L9QVgaQO.jpg',
    genre_ids: [28, 35],
    id: 897087,
    original_language: 'en',
    original_title: 'Freelance',
    overview:
      'An ex-special forces operative takes a job to provide security for a journalist as she interviews a dictator, but a military coup breaks out in the middle of the interview, they are forced to escape into the jungle where they must survive.',
    popularity: 1229.045,
    poster_path: '/7Bd4EUOqQDKZXA6Od5gkfzRNb0.jpg',
    release_date: '2023-01-05',
    title: 'Freelance',
    video: false,
    vote_average: 6.436,
    vote_count: 295,
  },
  {
    adult: false,
    backdrop_path: '/jVFeUR259RcW57mzhqJogV3QnLa.jpg',
    genre_ids: [28, 53, 18],
    id: 656156,
    original_language: 'ko',
    original_title: '보호자',
    overview:
      "After 10 years of incarceration on behalf of his employer, all Su-hyuk wants is a normal life - one he hopes will include his former girlfriend, Min-seo, and their daughter, In-bi. But once you've penetrated the upper echelons of the underworld, normal can prove hard to come by. Sometime in the past decade, meanwhile, Su-hyuk's employer has adopted an air of legitimacy. These days, the old gang steal and murder in the name of urban development. And they want the reluctant Su-hyuk on board.",
    popularity: 969.491,
    poster_path: '/ePwZs1oOh4pg8UZP8DuVZZeIn89.jpg',
    release_date: '2023-08-15',
    title: 'A Man of Reason',
    video: false,
    vote_average: 6.46,
    vote_count: 25,
  },
  {
    adult: false,
    backdrop_path: '/tLsc8SCFO0rMVgVyNm9XtfnyX84.jpg',
    genre_ids: [18, 9648, 53, 878],
    id: 726209,
    original_language: 'en',
    original_title: 'Leave the World Behind',
    overview:
      "A family's getaway to a luxurious rental home takes an ominous turn when a cyberattack knocks out their devices—and two strangers appear at their door.",
    popularity: 989.94,
    poster_path: '/5qhtTPWNqzM1eo9QIIf5cyIUeAA.jpg',
    release_date: '2023-11-22',
    title: 'Leave the World Behind',
    video: false,
    vote_average: 6.667,
    vote_count: 692,
  },
  {
    adult: false,
    backdrop_path: '/yOm993lsJyPmBodlYjgpPwBjXP9.jpg',
    genre_ids: [35, 10751, 14],
    id: 787699,
    original_language: 'en',
    original_title: 'Wonka',
    overview:
      'Willy Wonka – chock-full of ideas and determined to change the world one delectable bite at a time – is proof that the best things in life begin with a dream, and if you’re lucky enough to meet Willy Wonka, anything is possible.',
    popularity: 974.471,
    poster_path: '/qhb1qOilapbapxWQn9jtRCMwXJF.jpg',
    release_date: '2023-12-06',
    title: 'Wonka',
    video: false,
    vote_average: 7.256,
    vote_count: 195,
  },
];
